spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SpringSecurity?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: wangfei.*0928
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.109.100
    port: 6379
    database: 0
    password: 123456
